"""
holland/blocks.py — 积木块原理 (Building Blocks)
==================================================
Holland 原理⑦: 复杂系统由可复用积木块构成, 创新 = 积木块重组。
"Complex systems are generated by combining building blocks.
Reusing and recombining blocks yields novelty without starting
from scratch."

工程实现:
  - 积木块分解: 系统 → 可复用子组件
  - 重组创新: 跨域积木块映射 (类比 transposition)
  - 涌现检测: 新组合产生超出组件的功能

Holland 原文映射:
  "The building block hypothesis: complex systems are built
   from tested building blocks that are reused in new combinations."
   → 工程: 积木块 = 可验证的原子功能单元
"""

from __future__ import annotations

import math
from collections import defaultdict
from dataclasses import dataclass, field
from typing import Any


@dataclass
class BuildingBlock:
    """Holland 积木块: 可复用的原子组件。

    Holland: "A building block is a reusable component that
              has been tested and validated in multiple contexts."
    """
    name: str
    domain: str                           # 来源域
    functionality: str                    # 功能描述
    interfaces: list[str] = field(default_factory=list)  # 输入/输出
    reuse_count: int = 0                  # 跨域复用次数
    fitness: float = 0.0                  # 适应度 (验证成功率)
    dependencies: list[str] = field(default_factory=list)

    def compose_with(self, other: "BuildingBlock") -> "BuildingBlock | None":
        """尝试组合两个积木块。

        Holland: "Combining blocks is the primary act of innovation."
        """
        if not self.interfaces or not other.interfaces:
            return None
        # 检查接口兼容性: 第一个的输出匹配第二个的输入
        overlap = set(self.interfaces) & set(other.interfaces)
        if not overlap:
            return None

        return BuildingBlock(
            name=f"{self.name}+{other.name}",
            domain=f"{self.domain}×{other.domain}",
            functionality=f"{self.functionality} ∘ {other.functionality}",
            interfaces=list(set(self.interfaces + other.interfaces) - overlap),
            dependencies=sorted(set(self.dependencies + other.dependencies)),
        )


class BlockDecomposer:
    """积木块分解器: 将系统分解为可复用积木块。

    Holland: "Decomposing a system into blocks reveals
              the combinatorial space of possible innovations."
    """

    def __init__(self):
        self.blocks: dict[str, BuildingBlock] = {}
        self._compositions: list[BuildingBlock] = []
        self._domain_index: dict[str, list[str]] = defaultdict(list)

    def register(self, block: BuildingBlock):
        """注册积木块。"""
        self.blocks[block.name] = block
        self._domain_index[block.domain].append(block.name)

    def decompose(self, system_description: dict
                  ) -> list[BuildingBlock]:
        """从系统描述中提取积木块。

        Args:
            system_description: {
                "components": [{"name": ..., "function": ..., "inputs": [...], "outputs": [...]}],
                "domain": str,
            }
        """
        discovered = []
        for comp in system_description.get("components", []):
            block = BuildingBlock(
                name=comp["name"],
                domain=system_description.get("domain", "unknown"),
                functionality=comp.get("function", ""),
                interfaces=comp.get("inputs", []) + comp.get("outputs", []),
                dependencies=comp.get("dependencies", []),
            )
            self.register(block)
            discovered.append(block)
        return discovered

    def cross_domain_compose(self, domain_a: str, domain_b: str
                             ) -> list[BuildingBlock]:
        """跨域积木块重组 — 涌现新功能。

        Holland: "The most powerful innovations come from
                  combining blocks across domain boundaries."
        """
        new_blocks = []
        for a_name in self._domain_index.get(domain_a, []):
            for b_name in self._domain_index.get(domain_b, []):
                if a_name == b_name:
                    continue
                composed = self.blocks[a_name].compose_with(
                    self.blocks[b_name]
                )
                if composed:
                    composed.reuse_count = (
                        self.blocks[a_name].reuse_count +
                        self.blocks[b_name].reuse_count + 1
                    )
                    new_blocks.append(composed)
                    self._compositions.append(composed)

        return sorted(new_blocks, key=lambda b: b.reuse_count, reverse=True)

    def emergence_score(self, block: BuildingBlock) -> float:
        """积木块涌现度: 跨域 × 复用 × 组合复杂度。

        Holland: "Emergence is the appearance of properties
                  in the whole that are not in the parts."
        """
        n_domains = len(set(
            d for d in self._domain_index if block.name in self._domain_index[d]
        ))
        return min(1.0, (
            0.4 * min(block.reuse_count / 10.0, 1.0) +
            0.3 * min(n_domains / 5.0, 1.0) +
            0.3 * min(len(block.interfaces) / 8.0, 1.0)
        ))

    def suggest_innovations(self, target_domain: str, top_k: int = 5
                            ) -> list[tuple[BuildingBlock, float]]:
        """建议创新: 在其他域找到积木块, 映射到目标域。

        Holland: "Innovation is often just the application of
                  a building block from one domain to another."
        """
        suggestions = []
        for domain, names in self._domain_index.items():
            if domain == target_domain:
                continue
            for name in names:
                block = self.blocks[name]
                score = self.emergence_score(block)
                if score > 0.2:
                    suggestions.append((block, score))

        return sorted(suggestions, key=lambda x: x[1], reverse=True)[:top_k]
